#!/usr/bin/env python
"""Regenerate `docs/checks/` from the check registry and the injectors.

Run it with::

    uv run python scripts/generate_check_docs.py

SPEC §4.3 asks every check to document its rationale, the exact query it runs,
its default severity, and a worked synthetic example. All four already exist in
the code: the first three as check metadata, the fourth as the injector that
plants that check's leak. Writing them out by hand would mean four places to
keep in step, and prose drifts from code silently -- so the pages are generated
and a test asserts the committed ones match.

Every example below is produced by running the real check against data from
`ehrlint.synth`, so a page that claims a finding is a page where that finding
actually occurred.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "docs" / "checks"

HEADER = """<!--
Generated by scripts/generate_check_docs.py. Do not edit by hand: the
rationale, query, severity, and worked example all come from the code, and a
test asserts this file matches what the generator produces.
-->
"""

#: Hand-written context per check: what the pattern looks like in a real
#: project, and what to do about it. The generator supplies everything that is
#: derivable from the code; this supplies what is not.
GUIDANCE: dict[str, dict[str, str]] = {
    "LK001": {
        "looks_like": (
            'A feature pipeline that aggregates "all labs for this patient" without a '
            "cut-off at the index date, or a feature matrix whose as-of timestamp was "
            "taken from the outcome rather than the prediction moment."
        ),
        "fix": (
            "Cut every feature window at the index date, and carry an explicit as-of "
            "timestamp on the matrix so the cut is checkable rather than assumed."
        ),
        "note": (
            "The event-level branch is an **observation**, not an error. Outcomes and "
            "follow-up live after the index date, so every real dataset has post-index "
            "events; flagging their existence would make this check permanently red and "
            "teach you to ignore it. Supply `--features` to get the error branch, which "
            "can show that post-index information reached the matrix."
        ),
    },
    "LK002": {
        "looks_like": (
            "A diagnosis coded at discharge from the index visit. Its timestamp is the "
            "visit date, so a naive `time <= index_date` filter keeps it -- but the code "
            "was entered once the outcome was already known."
        ),
        "fix": (
            "Exclude the index encounter's codes from the feature window, or move the "
            "index date to the encounter's start and use only codes that predate it."
        ),
    },
    "LK003": {
        "looks_like": (
            "An insulin drip order before the index date in a DKA task, or a dialysis "
            "code before an end-stage-renal-disease outcome. The treatment implies the "
            "outcome, so a model learns the treatment."
        ),
        "fix": (
            "Decide whether the proxy belongs in the task at all. If a patient already "
            "receiving the treatment is not the population you mean to predict for, "
            "exclude them; if they are, the proxy has to come out of the features."
        ),
        "note": (
            "A warning, not an error: whether a code is a proxy is a clinical judgement "
            "about your cohort, and ehrlint only knows the list you gave it."
        ),
    },
    "LK004": {
        "looks_like": (
            "A negative label on a patient whose record stops three months after the "
            "index date in a two-year task. They were never observed long enough to "
            "have the outcome, so calling them a negative counts censoring as evidence."
        ),
        "fix": (
            "Require the full horizon for negatives and drop the rest, or switch to a "
            "time-to-event formulation that handles censoring explicitly."
        ),
    },
    "LK005": {
        "looks_like": (
            "A split taken over rows rather than patients, or a re-split after a merge "
            "that reintroduced patients already in the training set."
        ),
        "fix": "Split by subject, once, and keep the assignment in a file you audit.",
    },
    "LK006": {
        "looks_like": (
            "A random split described in the paper as temporal, or a temporal split "
            "taken on admission date while the index date is something else."
        ),
        "fix": (
            "Split on the same timestamp the task indexes on, and check the boundary "
            "rather than trusting the sort."
        ),
        "note": (
            "`error` when the task spec declares `splits.temporal: true`, `warning` "
            "otherwise. A declared property that does not hold is a broken claim; an "
            "undeclared one is a design question."
        ),
    },
    "LK007": {
        "looks_like": (
            "A label built from a registry flag or a chart review that used the whole "
            "record, then attached to an index date two years earlier. The label is "
            "correct about the patient and wrong about the prediction problem."
        ),
        "fix": (
            "Derive labels from events inside the declared window only, and keep the "
            "derivation in the same code path the audit sees."
        ),
    },
    "LK008": {
        "looks_like": (
            "Two admissions of the same patient under different subject ids landing in "
            "different splits, or several patients from one clinic visit sharing an "
            "encounter identifier."
        ),
        "fix": ("Group the split by the encounter or provider identifier, not only by subject."),
    },
    "LK009": {
        "looks_like": (
            "A patient registered twice -- at two sites, or before and after a record "
            "merge. The split is disjoint by id while not being disjoint by person, so "
            "LK005 is clean and the leak is invisible."
        ),
        "fix": (
            "Resolve the duplicates before splitting. A shared signature is a candidate "
            "for review, not a confirmed duplicate: twins and sparse demographics both "
            "produce collisions."
        ),
        "note": (
            "Deterministic, not probabilistic, and it **skips** rather than guessing "
            "when the demographics in your data distinguish too few profiles for a "
            "collision to be evidence. Reporting arithmetic as a finding would be the "
            "fabricated statistic this project forbids."
        ),
    },
    "LK010": {
        "looks_like": (
            "A positive label from an outcome three years after the index date in a "
            "two-year task -- usually a label query with no upper bound on time."
        ),
        "fix": (
            "Bound the outcome query by the horizon, and recount the positives "
            "afterwards. The prevalence will drop; that drop was always the truth."
        ),
    },
}


def worked_example(check_id: str) -> tuple[str, str]:
    """Run the check against clean and injected data, returning two blocks."""
    sys.path.insert(0, str(REPO / "src"))
    import polars as pl

    from ehrlint.audit import run_audit
    from ehrlint.context import AuditContext
    from ehrlint.inject import inject
    from ehrlint.io.features import build_feature_matrix
    from ehrlint.synth.generator import generate

    def context(data: object) -> AuditContext:
        return AuditContext.from_frames(
            data.events,  # type: ignore[attr-defined]
            task_spec=data.task,  # type: ignore[attr-defined]
            labels=data.labels,  # type: ignore[attr-defined]
            splits=data.splits_mapping(),  # type: ignore[attr-defined]
            features=(
                None
                if data.features is None  # type: ignore[attr-defined]
                else build_feature_matrix(data.features, source="synth")  # type: ignore[attr-defined]
            ),
        )

    dataset = generate(120, seed=0)

    clean_report = run_audit(context(dataset), [check_id])
    clean_finding = clean_report.finding(check_id)
    clean_block = (
        f"$ ehrlint audit --data clean/ --task task.yaml --checks {check_id}\n\n"
        f"{check_id} did not fire.\n"
        f"  {clean_finding.message if clean_finding else 'skipped'}\n"
        f"exit code {clean_report.exit_code}"
    )

    injection = inject(dataset, check_id, n=4, seed=0)
    report = run_audit(context(injection.dataset), [check_id])
    finding = report.finding(check_id)
    if finding is None:  # pragma: no cover - would be a duality failure
        raise SystemExit(f"{check_id} produced no finding on its own injected leak")

    rate = "-" if finding.subject_rate is None else f"{finding.subject_rate * 100:.1f}%"
    lines = [
        f"$ ehrlint audit --data leaky/ --task task.yaml --checks {check_id}",
        "",
        f"{finding.check_id} {finding.name}  [{finding.severity.value}]",
        f"  {finding.message}",
        f"  affected: {finding.n_subjects} of {finding.n_total_subjects} subject(s) "
        f"({rate}), {finding.n_rows} row(s)",
        "",
        "  example rows:",
    ]
    columns = finding.example_columns[:5]
    widths = {
        c: max(len(c), *(len(str(r.get(c, ""))[:24]) for r in finding.examples[:3] or [{}]))
        for c in columns
    }
    lines.append("    " + "  ".join(f"{c:<{widths[c]}}" for c in columns))
    for row in finding.examples[:3]:
        lines.append(
            "    " + "  ".join(f"{str(row.get(c, ''))[:24]:<{widths[c]}}" for c in columns)
        )
    lines.extend(["", f"exit code {report.exit_code}"])
    del pl
    return clean_block, "\n".join(lines)


def page(check: object) -> str:
    """Render one check's page."""
    metadata = check.metadata()  # type: ignore[attr-defined]
    check_id = metadata["id"]
    guidance = GUIDANCE.get(check_id, {})
    clean_block, leaky_block = worked_example(check_id)

    parts = [
        HEADER,
        f"# {check_id} — `{metadata['name']}`",
        "",
        f"**{metadata['description']}**",
        "",
        f"| | |\n| --- | --- |\n| default severity | `{metadata['severity_default']}` |"
        f"\n| injector | `ehrlint.inject.inject_{check_id.lower()}` |",
        "",
        "## Why this matters",
        "",
        metadata["rationale"],
        "",
    ]

    if guidance.get("looks_like"):
        parts += ["## What it looks like in practice", "", guidance["looks_like"], ""]
    if guidance.get("note"):
        parts += ["## A note on severity", "", guidance["note"], ""]

    parts += [
        "## The query it runs",
        "",
        "```sql",
        _query_of(check),
        "```",
        "",
        "## Worked example",
        "",
        "On the clean synthetic cohort, which is clean by construction:",
        "",
        "```text",
        clean_block,
        "```",
        "",
        f"With the matching leak planted by `ehrlint.inject.inject_{check_id.lower()}`:",
        "",
        "```text",
        leaky_block,
        "```",
        "",
        "Reproduce both:",
        "",
        "```bash",
        "ehrlint synth --out clean/ --n-subjects 120 --seed 0",
        f"ehrlint synth --out leaky/ --n-subjects 120 --seed 0 --inject {check_id}",
        "ehrlint audit --data leaky/ --task leaky/task.yaml \\",
        f"  --labels leaky/labels.parquet --splits leaky/splits.json --checks {check_id}",
        "```",
        "",
    ]

    if guidance.get("fix"):
        parts += ["## What to do about it", "", guidance["fix"], ""]

    parts += [
        "## When it skips",
        "",
        "A skip is not a pass. This check reports a skip, with the reason, when its "
        "inputs are not available — see [reading a report](../reports.md).",
        "",
    ]
    return "\n".join(parts)


def _query_of(check: object) -> str:
    """The query string a check emits, taken from a real run."""
    sys.path.insert(0, str(REPO / "src"))
    from ehrlint.audit import run_audit
    from ehrlint.context import AuditContext
    from ehrlint.inject import inject
    from ehrlint.io.features import build_feature_matrix
    from ehrlint.synth.generator import generate

    check_id = check.id  # type: ignore[attr-defined]
    dataset = generate(120, seed=0)
    injection = inject(dataset, check_id, n=4, seed=0)
    data = injection.dataset
    ctx = AuditContext.from_frames(
        data.events,
        task_spec=data.task,
        labels=data.labels,
        splits=data.splits_mapping(),
        features=(
            None if data.features is None else build_feature_matrix(data.features, source="synth")
        ),
    )
    finding = run_audit(ctx, [check_id]).finding(check_id)
    return finding.query if finding else "-- the check skipped on this input"


def index_page(checks: list[object]) -> str:
    """The battery table."""
    rows = [
        f"| [{c.metadata()['id']}]({c.metadata()['id'].lower()}.md) "  # type: ignore[attr-defined]
        f"| `{c.metadata()['name']}` "  # type: ignore[attr-defined]
        f"| {c.metadata()['description']} "  # type: ignore[attr-defined]
        f"| `{c.metadata()['severity_default']}` |"  # type: ignore[attr-defined]
        for c in checks
    ]
    return "\n".join(
        [
            HEADER,
            "# The check battery",
            "",
            "Ten checks, each with a rationale, the exact query it runs, and a worked",
            "example on synthetic data. Every one has a matching injector that plants",
            "exactly the leak it looks for, which is how each is tested against ground",
            "truth rather than against an opinion.",
            "",
            "| ID | Name | What it flags | Default |",
            "| --- | --- | --- | --- |",
            *rows,
            "",
            "## Severity policy",
            "",
            "`error` — the task is invalid as defined. Post-index features, split",
            "overlap, a label built from future information. The default `--fail-on`.",
            "",
            "`warning` — a suspicious pattern that needs a human. Proxies and temporal",
            "edge cases, where whether it is a problem depends on your cohort.",
            "",
            "`info` — descriptive statistics. These never fail a run, which is why",
            "`--fail-on info` is refused rather than accepted as a synonym for",
            "`--fail-on warning`.",
            "",
            "## Two things every check does",
            "",
            "**Carries its evidence.** Each finding references the rows that triggered",
            "it and the query that found them. A count with no rows is rejected by a",
            "validator.",
            "",
            "**Says when it cannot run.** A check with missing inputs reports a skip and",
            "a reason. It never reports a pass it did not earn.",
            "",
        ]
    )


def main() -> int:
    sys.path.insert(0, str(REPO / "src"))
    from ehrlint.checks.base import all_checks

    OUT.mkdir(parents=True, exist_ok=True)
    checks = all_checks()

    written = [OUT / "index.md"]
    (OUT / "index.md").write_text(index_page(list(checks)), encoding="utf-8")
    for check in checks:
        path = OUT / f"{check.id.lower()}.md"
        path.write_text(page(check), encoding="utf-8")
        written.append(path)

    for path in sorted(written):
        print(f"wrote {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
